#!/usr/bin/perl

use IO::Socket::INET;
use strict;
use warnings;

$| = 1;
my $socket;
my $command;
my $port = 443;
my $upper = 255;
my $lower = 100;
my $fh;


sub generate(){

    my $i = int(rand($upper - $lower)) + $lower;
    my $j = int(rand($upper - $lower)) + $lower;
    my $k = int(rand($upper - $lower)) + $lower;
    my $l = int(rand($upper - $lower)) + $lower;
    $command = $i;
    $command .= ".";
    $command .= $j;
    $command .= ".";
    $command .= $k;
    $command .= ".";
    $command .= $l;

    $socket = IO::Socket::INET->new (
    PeerHost => $command,
    PeerPort => $port,
    Proto => 'tcp',
    Timeout => 2,
    ) or return;

    `echo $command >> addresses.txt`;

    $socket->close();
    return;

}

sub connectAddr(){

my $filename = 'addresses.txt';
if (open(my $fh, '<:encoding(UTF-8)', $filename)) {

  while (my $address = <$fh>) {

    chomp $address;

    $socket = IO::Socket::INET->new (
    PeerHost => $address,
    PeerPort => $port,
    Proto => 'tcp',
    Timeout => 3,
    ) or next;

    sleep(5);

    $socket->close();

  }
} else {
  warn "Could not open file '$filename' $!";
}

return;

}

while(1){

    generate();
    connectAddr();

}
