#!/usr/bin/perl

use IO::Socket::INET;

$| = 1;
my $socket;



my $command;
my $port = 443;
my $upper = 255;
my $lower = 100;
my $timer;



while(1){

START:
    my $i = int(rand($upper - $lower)) + $lower;
    my $j = int(rand($upper - $lower)) + $lower;
    my $k = int(rand($upper - $lower)) + $lower;
    my $l = int(rand($upper - $lower)) + $lower;
    $timer = int(rand(6)) + 1;
    $command = $i;
    $command .= ".";
    $command .= $j;
    $command .= ".";
    $command .= $k;
    $command .= ".";
    $command .= $l;

    $socket = IO::Socket::INET->new (
    PeerHost => $command,
    PeerPort => $port,
    Proto => 'tcp',
    Timeout => 1,
    ) or print "No Connection\n" and goto START;

    print "Success! $command \n";
    `echo $command >> addresses.txt`;





}
