#!/usr/bin/perl


my $command;
my $upper = 255;
my $lower = 100;
my $timer;

while(1){

    my $i = int(rand($upper - $lower)) + $lower;
    my $j = int(rand($upper - $lower)) + $lower;
    my $k = int(rand($upper - $lower)) + $lower;
    my $l = int(rand($upper - $lower)) + $lower;
    $timer = int(rand(6)) + 1;
    $command = $i;
    $command .= ".";
    $command .= $j;
    $command .= ".";
    $command .= $k;
    $command .= ".";
    $command .= $l;
    print $command;
    `nc -w $timer -c $command 80 &> /dev/null`;

}
