#!/usr/bin/perl

my $command;
my $i;
my $j;
my $k;
my $l;
my $upper = 255;
my $lower = 100;

while(1){
  $i = int(rand($upper - $lower)) + $lower;
  $j = int(rand($upper - $lower)) + $lower; 
  $k = int(rand($upper - $lower)) + $lower; 
  $l = int(rand($upper - $lower)) + $lower; 
  $command = $i;
  $command .= ".";
  $command .= $j;
  $command .= ".";
  $command .= $k;
  $command .= ".";
  $command .= $l;
  `nc -w 5 $command 80 &> /dev/null`; 
}
